### ISSUE TITLE
allas_conf trouble with python 3.9.2 and python 3.9.1

### ISSUE THREAD

**Issue by samumantha** [CSCfi/allas-cli-utils#3]
Fyi:

The creation of the conda environment works fine with both python 3.9 versions I tried, however when running allas_conf it is not able to finish the configuration for s3cmd. 

When trying the s3cmd --configure directly it ended up with `module 'base64' has no attribute 'encodestring'`.
As well as some suggestions to use `==` instead of `ìs` somewhere in s3cmd code when running s3cmd.
Therefore tried with older Python version.

**Setting up the environment with Python pinned to version 3.8 it works!**

**Comment by v-iashin** [comment]
I think I had a similar problem. 

Running `allas-conf --mode s3` was giving me 
```
Configuration aborted. Changes were NOT saved.
grep: /users/<my_name>/.s3cfg_1793830: No such file or directory

s3cmd configuration ready.
```

I am confirming that running `allas-conf` from within a conda environment has a lower Python version (3.7.11) helps with this issue.

The `/appl/opt/csc-tools/allas-cli-utils/allas/bin/python` is 3.10.4.

**Comment by kkmattil** [comment]
Updating s3cmd to the latest version could solve this issue.
